### ISSUE TITLE
Console not registering variables

### ISSUE THREAD

**Issue by CookieKenneth** [LordCage/bananabot#6]
client.on('ready', () => {
  console.log(`Logged in as ${client.user.tag}!`);
});

**Comment by LordCage** [comment]
the ! isn't right it needs to be quoted. the bot won't allow that.

**Comment by CookieKenneth** [comment]
the "!" is outside of the {} though.

**Comment by LordCage** [comment]
its not quoted. and i believe ! <- this can't be "naked" try it wthout the ! in general.
